version: '3'

services:
  frontend:
    build:
      context: ./typescript/simple-mercari-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:9000
    depends_on:
      - api
    networks:
      - mercari-network

  api:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://frontend:3000
    networks:
      - mercari-network

networks:
  mercari-network:
    driver: bridge
