#build2024/web:latest
# ベースとなるイメージを指定
FROM node:latest

# アプリケーションのディレクトリを作成
WORKDIR /app

# ローカルのpackage.jsonとpackage-lock.jsonをコピー
COPY package*.json ./

# npmパッケージをインストール
RUN npm install

# ローカルのソースコードをコピー
COPY . .

# TypeScriptをビルド
RUN npm run build

# ポート3000を公開
EXPOSE 3000

# アプリケーションを起動
CMD ["npm", "start"]
